###
POST http://localhost:3000/user/register
Content-Type: application/json
api_key: prueba_api_random

{
"email": "test2@test.com",
"password": "password2"
}
###

PUT http://localhost:3000/user/validation
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjU5MiwiZXhwIjoxNzQ2NjE5NzkyfQ.CdwjJN0up96dwkkjH4D4MZc_1v2EvTb2DmN3bcw9Atg

{
  "codigo": 100682
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
  "email": "test1@test.com",
  "password": "password1"
}

###

### Actualizar datos personales del usuario
PUT http://localhost:3000/user/register
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY

{
  "name": "José",
  "surnames": "García Pérez",
  "nif": "40000001A"
}

###

PATCH http://localhost:3000/user/company
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY

{
  "company": {
    "name": "Servitop2, SL.",
    "cif": "BXXXXXXXY",
    "street": "Carlos V",
    "number": 22,
    "postal": 28936,
    "city": "Móstoles",
    "province": "Madrid"
  }
}

###
PATCH http://localhost:3000/user/logo
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
Content-Type: multipart/form-data; boundary=----ejemplo

------ejemplo
Content-Disposition: form-data; name="logo"; filename="logo1.png"
Content-Type: image/png

< C:\Users\Usuario\Downloads\logo1.png
------ejemplo--
###

GET http://localhost:3000/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
DELETE http://localhost:3000/user?soft=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U5OGUwNjQwMTQzYzBkZGI2ZGYyZjkiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MzM1OTU1MCwiZXhwIjoxNzQzMzY2NzUwfQ.nz1A9kBV-Ts9cbqGktpSEn5Rokq8fa1wwn7VuESfA3A
###
DELETE http://localhost:3000/user?soft=false
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2U5OGUwNjQwMTQzYzBkZGI2ZGYyZjkiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0MzM1OTU1MCwiZXhwIjoxNzQzMzY2NzUwfQ.nz1A9kBV-Ts9cbqGktpSEn5Rokq8fa1wwn7VuESfA3A
###

### cosas practica 2

###
POST http://localhost:3000/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
Content-Type: application/json

{
  "name": "Cliente Ejemplo 2",
  "cif": "B12345657"
}
###
PATCH http://localhost:3000/client/681b3207c579e453de05415d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
Content-Type: application/json

{
  "name": "Nuevo nombre"
}
###
GET http://localhost:3000/client
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
GET http://localhost:3000/client/681b3207c579e453de05415d
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
DELETE http://localhost:3000/client/681b3207c579e453de05415d?soft=true
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
GET http://localhost:3000/client/archived
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
PATCH http://localhost:3000/client/681b3207c579e453de05415d/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
POST http://localhost:3000/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
Content-Type: application/json

{
  "name": "Proyecto Ejemplo",
  "description": "Proyecto de construcción de edificio",
  "address": "Calle Mayor 15",
  "postalCode": "28001",
  "city": "Madrid",
  "client": "681b3207c579e453de05415d"
}
###
GET http://localhost:3000/project
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
GET http://localhost:3000/project/681b32b9c579e453de054175
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
PATCH http://localhost:3000/project/681b32b9c579e453de054175
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
Content-Type: application/json

{
  "name": "Nuevo nombre del proyecto",
  "address": "Nueva dirección",
  "postalCode": "28045"
}
###
### En el de DELETE si quieres hacerlo soft asi sirve , sino añades ?soft=false
###
DELETE http://localhost:3000/project/681b32b9c579e453de054175
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
GET http://localhost:3000/project/archived
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
PATCH http://localhost:3000/project/681b32b9c579e453de054175/restore
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
POST http://localhost:3000/deliverynote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
Content-Type: application/json

{
  "client": "681b3207c579e453de05415d",
  "project": "681b32b9c579e453de054175",
  "description": "Instalación eléctrica de oficinas",
  "materials": [
    {
      "description": "Cableado eléctrico",
      "quantity": 200,
      "unit": "metros",
      "price": 0.5
    }
  ],
  "hours": [
    {
      "worker": "Juan Pérez",
      "hours": 8,
      "pricePerHour": 20
    }
  ],
  "totalCost": 300
}
###
GET http://localhost:3000/deliverynote
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
GET http://localhost:3000/deliverynote/681b337cc579e453de05418a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
GET http://localhost:3000/deliverynote/pdf/681b337cc579e453de05418a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
DELETE http://localhost:3000/deliverynote/681b337cc579e453de05418a
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2ODFiMzE3MGM1NzllNDUzZGUwNTQxNGMiLCJyb2xlIjoidXNlciIsImlhdCI6MTc0NjYxMjYyMywiZXhwIjoxNzQ2NjE5ODIzfQ.kjNdHH1zxH5SXfqe29NJ3I0G8K_hP9vt_Gz_vTjoMdY
###
###Este ultimo es para probar que el slack funciona correctamente
###
GET http://localhost:3000/testSlack/test-error
###